<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "person_manager"
 *
 * Auto generated by Extension Builder 2015-02-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Person Manager',
    'description' => 'A TYPO3 extension to manage user/subscriber data. Works perfectly with the extension newsletter.',
    'category' => 'plugin',
    'author' => 'Philipp Parzer',
    'author_email' => 'p.parzer@siwa.at',
    'author_company' => 'SIWA Online GmbH',
    'state' => 'stable',
    'version' => '6.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.4.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
            'newsletter' => '',
        ],
    ],
];
